[iosevka-nerd-font]
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Iosevka.zip"
extract = "IosevkaNerdFont-[^.]+\\.ttf"

[iosevka-term-nerd-font]
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/IosevkaTerm.zip"
extract = "IosevkaTermNerdFont-[^.]*\\.ttf"

[pretendard]
url = "https://github.com/orioncactus/pretendard/releases/download/v1.3.9/Pretendard-1.3.9.zip"
extract = "(PretendardVariable.ttf$|Pretendard-[^.]+\\.otf$)"

[silver]
url = "https://poppyworks.itch.io/silver"
manual = true
