customizing = [
    'arcticicestudio.nord-visual-studio-code',
    'vscode-icons-team.vscode-icons',
]

language-support = [
    'tamasfe.even-better-toml',
    'TheNuProjectContributors.vscode-nushell-lang',
    'redhat.vscode-yaml',
]

git = ['eamodio.gitlens']

quality-of-life = ['pflannery.vscode-versionlens']

base = ['ms-vscode-remote.remote-wsl']
